# Generated by Django 5.1.5 on 2025-01-24 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "chassis_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "engine_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("vehicle_photos", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
                "db_table": "vehicles",
            },
        ),
    ]
