# Generated by Django 5.1.5 on 2025-01-24 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garages", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("case_name", models.CharField(max_length=255)),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("ACCIDENT_REPORT", "Accident Report"),
                            ("ACCIDENT_REPORT_EVALUATED", "Accident Report Evaluated"),
                            ("CLAIM_CREATED", "Claim Created"),
                            ("CLAIM_ASSIGNED_TO_GARAGE", "Claim Assigned to Garage"),
                            (
                                "CLAIM_ESTIMATE_GIVEN_BY_GARAGE",
                                "Claim Estimate Given by Garage",
                            ),
                        ],
                        default="ACCIDENT_REPORT",
                        max_length=50,
                    ),
                ),
                ("accident_photos", models.JSONField(default=dict)),
                ("accident_date", models.DateField()),
                ("accident_time", models.TimeField()),
                ("accident_location", models.CharField(max_length=255)),
                (
                    "weather_conditions",
                    models.CharField(
                        choices=[
                            ("CLEAR", "Clear"),
                            ("RAINY", "Rainy"),
                            ("FOGGY", "Foggy"),
                            ("SNOWY", "Snowy"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number_of_vehicles", models.IntegerField()),
                ("injuries", models.BooleanField(default=False)),
                ("police_report", models.BooleanField(default=False)),
                ("witness", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "case_severity",
                    models.CharField(
                        choices=[("MINOR", "Minor"), ("MAJOR", "Major")], max_length=20
                    ),
                ),
                ("claim_form", models.UUIDField(blank=True, null=True)),
                (
                    "estimate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("case_created_at", models.DateTimeField(auto_now_add=True)),
                ("case_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "garage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="garages.garage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "case",
                "verbose_name_plural": "cases",
                "db_table": "cases",
                "ordering": ["-case_created_at"],
            },
        ),
    ]
