# Generated by Django 5.1.5 on 2025-01-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="estimate",
        ),
        migrations.AddField(
            model_name="case",
            name="estimate_file",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
