# Generated by Django 5.1.5 on 2025-01-24 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE_PHOTO", "Vehicle Photo"),
                            ("ACCIDENT_PHOTO", "Accident Photo"),
                            ("CLAIM_FORM", "Claim Form"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
                "db_table": "files",
            },
        ),
    ]
