# Generated by Django 5.1.5 on 2025-01-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("VEHICLE_PHOTO", "Vehicle Photo"),
                    ("ACCIDENT_PHOTO", "Accident Photo"),
                    ("CLAIM_FORM", "Claim Form"),
                    ("ESTIMATE", "Garage Estimate"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
