# Generated by Django 5.1.5 on 2025-01-24 18:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_file_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=core.models.File.get_upload_path),
        ),
    ]
